version: '3.3'

services:
  face-detector-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables" 
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/face-detector-api
    command: bash -c "rm -rf node_modules/; npm install; npm start"
    working_dir: /usr/src/face-detector-api
    environment:
      POSTGRES_URI: postgres://badrri:secret123@postgres:5432/face-detector-db
      JWT_SECRET: '06c219e5bc8378f3a8a3f83b4b7e4649'
      REDIS_URI: redis://redis:6379
    links:
      - postgres
    ports:
      - "3004:3004"
  # Postgres database
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: badrri
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: face-detector-db
      POSTGRES_HOST: postgres
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"